export const message_list = [
    {
        message:"hii",
        outgoing:true,
        createdAt:"12:00pm",
        status:"read"
    },
    {
        message:"hy",
        outgoing:false,
        createdAt:"12:01pm",
        status:"read"
    },
    {
        message:"kya kr rha h",
        outgoing:true,
        createdAt:"12:01pm",
        status:"unread"
    },
    {
        message:"kha gya ",
        outgoing:true,
        createdAt:"12:02pm",
        status:"unread"
    },
    {
        message:"oyy",
        outgoing:true,
        createdAt:"12:05pm",
        status:"unread"
    },
    {
        message:"hii",
        outgoing:true,
        createdAt:"12:00pm",
        status:"read"
    },
    {
        message:"hy",
        outgoing:false,
        createdAt:"12:01pm",
        status:"read"
    },
    {
        message:"kya kr rha h",
        outgoing:true,
        createdAt:"12:01pm",
        status:"unread"
    },
    {
        message:"kha gya ",
        outgoing:true,
        createdAt:"12:02pm",
        status:"unread"
    },
    {
        message:"oyy",
        outgoing:true,
        createdAt:"12:05pm",
        status:"unread"
    },
    {
        message:"hii",
        outgoing:true,
        createdAt:"12:00pm",
        status:"read"
    },
    {
        message:"hy",
        outgoing:false,
        createdAt:"12:01pm",
        status:"read"
    },
    {
        message:"kya kr rha h",
        outgoing:true,
        createdAt:"12:01pm",
        status:"unread"
    },
    {
        message:"kha gya ",
        outgoing:true,
        createdAt:"12:02pm",
        status:"unread"
    },
    {
        message:"oyy",
        outgoing:true,
        createdAt:"12:05pm",
        status:"unread"
    },
    {
        message:"hii",
        outgoing:true,
        createdAt:"12:00pm",
        status:"read"
    },
    {
        message:"hy",
        outgoing:false,
        createdAt:"12:01pm",
        status:"read"
    },
    {
        message:"kya kr rha h",
        outgoing:true,
        createdAt:"12:01pm",
        status:"unread"
    },
    {
        message:"kha gya ",
        outgoing:true,
        createdAt:"12:02pm",
        status:"unread"
    },
    {
        message:"oyy",
        outgoing:true,
        createdAt:"12:05pm",
        status:"unread"
    },
    {
        message:"hii",
        outgoing:true,
        createdAt:"12:00pm",
        status:"read"
    },
    {
        message:"hy",
        outgoing:false,
        createdAt:"12:01pm",
        status:"read"
    },
    {
        message:"kya kr rha h",
        outgoing:true,
        createdAt:"12:01pm",
        status:"unread"
    },
    {
        message:"kha gya ",
        outgoing:true,
        createdAt:"12:02pm",
        status:"unread"
    },
    {
        message:"oyy",
        outgoing:true,
        createdAt:"12:05pm",
        status:"unread"
    },
]